### ISSUE TITLE
Only connecting

### ISSUE THREAD

**Issue by Silverquest91** [v10networkscom/saltychat-redm#11]
Im Only Connecting in game websocket html 29 .. i have no idea can anyone help me ?

**Comment by Silverquest91** [comment]
![Screenshot 2022-01-30 165644](https://user-images.githubusercontent.com/82270920/151707058-c9eca423-1e4f-4d16-948f-e941ec70ab00.png)

**Comment by BlackFlash5** [comment]
https://github.com/v10networkscom/saltychat-docs/blob/master/faq.md#cfx-nui-stuck-at-connecting

**Comment by Silverquest91** [comment]
i have a Fivem server on the same server running on this works saltychat but on redm dosnt why
