### ISSUE TITLE
Salty chat port switch 8088 to 38088 client side issues

### ISSUE THREAD

**Issue by azarathkhan** [v10networkscom/saltychat-redm#3]
We noticed salty chat changed their port from 8088 to 38088 via the resource.

This caused issues for a lot of our clients, as their AppData\Roaming\TS3Client\plugins\SaltyChat\settings.json was keeping 8088 port as default even after an update to salty chat tsplugin 2.0

We've asked our users to delete the settings.json file and restart teamspeak so that it recreates the settings file with the correct new default port 38088.

Please fix the plugin so that it automatically changes the users port from 8088 to 38088 regardless of what their current settings.json says.

**Comment by BlackFlash5** [comment]
This is the RedM repo and not the place for a discussion regarding the plugin, move it to the discord, or to the docs repo.
You can also reset the config in the settings and restart TeamSpeak after that, there is no need to delete the json file.
