### ISSUE TITLE
Under linux server

### ISSUE THREAD

**Issue by Gentil-Boo** [v10networkscom/saltychat-redm#5]
There is way to make it work on a linux server?

**Comment by BlackFlash5** [comment]
There is, just do what the setup steps say.
CFX server is using mono so there are no issues using this on a linux server.

**Comment by Gentil-Boo** [comment]
When I use dotnet build, I got errors. 

.NETFramework,Version=v4.5.2 needed apparently, I use sdk/5.0.202 cant find 4.5.2 on linux

and when I use mono with xbuild I got 37 errors
