### ISSUE TITLE
RedM Saltychat Onesync

### ISSUE THREAD

**Issue by ChicoTeVee** [v10networkscom/saltychat-redm#7]
Hey guys!

Actually we use Saltychat for FiveM and also for RedM. Both works very fine.
A few days ago RedM released an "Alpha" Stage for RedM Onesync. We updated our Server for it and Start test.
Now we found an issue with Saltychat. The Players can hear other Players over the Map. Its very weird and confusing.

Player 1 can hear Player 2, Player 3 can hear Player 4 but nothing else. Player 2 can hear Player 1, idk how to explain it correctly.
One time i walk to Player 1 and can hear Player 3. I walked out of Range and both gets muted.. it was very strange but we must stop the Test-Phase because with this issue its hard to make "Roleplay".

Is there any Update planned for the Onesync Compatibility?

Greezt Chico :)

**Comment by BlackFlash5** [comment]
OneSync for RedM isn't meant for production yet.
The only reason why this scripts exists in the first place, is the fact that there was no OneSync support for RedM, it's just an old version of the FiveM non-1s script with replaced natives.
If you wan't to use OneSync you can use the FiveM version replace the natives.

**Comment by ChicoTeVee** [comment]
Is there any explain wich Natives need to be changed?

**Comment by BlackFlash5** [comment]
Introduced 1s support in 56dc48797a0f54c2cc3a0ed46c7e4e1d315f605f, feedback is appreciated.

**Comment by BlackFlash5** [comment]
1s compatibility was verified internally.
