### ISSUE TITLE
Can we get a tutorial on how to instal the onesync build please. 

### ISSUE THREAD

**Issue by Antarcy** [v10networkscom/saltychat-redm#8]
Can we get a tutorial on how to instal the onesync build please. 
Cause when i build and instal the pulgin on a onesync redm serveur it doenst detect the player near each other

**Comment by BlackFlash5** [comment]
Read the [announcement](https://forum.cfx.re/t/technical-preview-onesync-now-available-for-redm/4413410#how-to-use-it-2)?
